// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package token_metadata

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Given a token account containing the master edition token to prove authority, and a brand new non-metadata-ed mint with one token
// make a new Metadata + Edition that is a child of the master edition denoted by this authority token.
type MintNewEditionFromMasterEditionViaToken struct {
	Args *MintNewEditionFromMasterEditionViaTokenArgs

	// [0] = [WRITE] newMetadataKey
	// ··········· New Metadata key (pda of ['metadata', program id, mint id])
	//
	// [1] = [WRITE] newEditionPDA
	// ··········· New Edition (pda of ['metadata', program id, mint id, 'edition'])
	//
	// [2] = [WRITE] masterRecordEditionV2
	// ··········· Master Record Edition V2 (pda of ['metadata', program id, master metadata mint id, 'edition'])
	//
	// [3] = [WRITE] mintOfNewToken
	// ··········· Mint of new token - THIS WILL TRANSFER AUTHORITY AWAY FROM THIS KEY
	//
	// [4] = [WRITE] editionPDA
	// ··········· Edition pda to mark creation - will be checked for pre-existence. (pda of ['metadata', program id, master metadata mint id, 'edition', edition_number])
	// ··········· where edition_number is NOT the edition number you pass in args but actually edition_number = floor(edition/EDITION_MARKER_BIT_SIZE).
	//
	// [5] = [SIGNER] mintAuthority
	// ··········· Mint authority of new mint
	//
	// [6] = [SIGNER] payer
	// ··········· payer
	//
	// [7] = [SIGNER] ownerOfToken
	// ··········· owner of token account containing master token (#8)
	//
	// [8] = [] tokenAccount
	// ··········· token account containing token from master metadata mint
	//
	// [9] = [] updateAuthorityInfo
	// ··········· Update authority info for new metadata
	//
	// [10] = [] masterRecordMetadata
	// ··········· Master record metadata account
	//
	// [11] = [] tokenProgram
	// ··········· Token program
	//
	// [12] = [] systemProgram
	// ··········· System program
	//
	// [13] = [] rentInfo
	// ··········· Rent info
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
}

// NewMintNewEditionFromMasterEditionViaTokenInstructionBuilder creates a new `MintNewEditionFromMasterEditionViaToken` instruction builder.
func NewMintNewEditionFromMasterEditionViaTokenInstructionBuilder() *MintNewEditionFromMasterEditionViaToken {
	nd := &MintNewEditionFromMasterEditionViaToken{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 14),
	}
	return nd
}

// SetArgs sets the "args" parameter.
func (inst *MintNewEditionFromMasterEditionViaToken) SetArgs(args MintNewEditionFromMasterEditionViaTokenArgs) *MintNewEditionFromMasterEditionViaToken {
	inst.Args = &args
	return inst
}

// SetNewMetadataKeyAccount sets the "newMetadataKey" account.
// New Metadata key (pda of ['metadata', program id, mint id])
func (inst *MintNewEditionFromMasterEditionViaToken) SetNewMetadataKeyAccount(newMetadataKey ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(newMetadataKey).WRITE()
	return inst
}

// GetNewMetadataKeyAccount gets the "newMetadataKey" account.
// New Metadata key (pda of ['metadata', program id, mint id])
func (inst *MintNewEditionFromMasterEditionViaToken) GetNewMetadataKeyAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetNewEditionPDAAccount sets the "newEditionPDA" account.
// New Edition (pda of ['metadata', program id, mint id, 'edition'])
func (inst *MintNewEditionFromMasterEditionViaToken) SetNewEditionPDAAccount(newEditionPDA ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(newEditionPDA).WRITE()
	return inst
}

// GetNewEditionPDAAccount gets the "newEditionPDA" account.
// New Edition (pda of ['metadata', program id, mint id, 'edition'])
func (inst *MintNewEditionFromMasterEditionViaToken) GetNewEditionPDAAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetMasterRecordEditionV2Account sets the "masterRecordEditionV2" account.
// Master Record Edition V2 (pda of ['metadata', program id, master metadata mint id, 'edition'])
func (inst *MintNewEditionFromMasterEditionViaToken) SetMasterRecordEditionV2Account(masterRecordEditionV2 ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(masterRecordEditionV2).WRITE()
	return inst
}

// GetMasterRecordEditionV2Account gets the "masterRecordEditionV2" account.
// Master Record Edition V2 (pda of ['metadata', program id, master metadata mint id, 'edition'])
func (inst *MintNewEditionFromMasterEditionViaToken) GetMasterRecordEditionV2Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetMintOfNewTokenAccount sets the "mintOfNewToken" account.
// Mint of new token - THIS WILL TRANSFER AUTHORITY AWAY FROM THIS KEY
func (inst *MintNewEditionFromMasterEditionViaToken) SetMintOfNewTokenAccount(mintOfNewToken ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(mintOfNewToken).WRITE()
	return inst
}

// GetMintOfNewTokenAccount gets the "mintOfNewToken" account.
// Mint of new token - THIS WILL TRANSFER AUTHORITY AWAY FROM THIS KEY
func (inst *MintNewEditionFromMasterEditionViaToken) GetMintOfNewTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

// SetEditionPDAAccount sets the "editionPDA" account.
// Edition pda to mark creation - will be checked for pre-existence. (pda of ['metadata', program id, master metadata mint id, 'edition', edition_number])
// where edition_number is NOT the edition number you pass in args but actually edition_number = floor(edition/EDITION_MARKER_BIT_SIZE).
func (inst *MintNewEditionFromMasterEditionViaToken) SetEditionPDAAccount(editionPDA ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(editionPDA).WRITE()
	return inst
}

// GetEditionPDAAccount gets the "editionPDA" account.
// Edition pda to mark creation - will be checked for pre-existence. (pda of ['metadata', program id, master metadata mint id, 'edition', edition_number])
// where edition_number is NOT the edition number you pass in args but actually edition_number = floor(edition/EDITION_MARKER_BIT_SIZE).
func (inst *MintNewEditionFromMasterEditionViaToken) GetEditionPDAAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[4]
}

// SetMintAuthorityAccount sets the "mintAuthority" account.
// Mint authority of new mint
func (inst *MintNewEditionFromMasterEditionViaToken) SetMintAuthorityAccount(mintAuthority ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(mintAuthority).SIGNER()
	return inst
}

// GetMintAuthorityAccount gets the "mintAuthority" account.
// Mint authority of new mint
func (inst *MintNewEditionFromMasterEditionViaToken) GetMintAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[5]
}

// SetPayerAccount sets the "payer" account.
// payer
func (inst *MintNewEditionFromMasterEditionViaToken) SetPayerAccount(payer ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(payer).SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
// payer
func (inst *MintNewEditionFromMasterEditionViaToken) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[6]
}

// SetOwnerOfTokenAccount sets the "ownerOfToken" account.
// owner of token account containing master token (#8)
func (inst *MintNewEditionFromMasterEditionViaToken) SetOwnerOfTokenAccount(ownerOfToken ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(ownerOfToken).SIGNER()
	return inst
}

// GetOwnerOfTokenAccount gets the "ownerOfToken" account.
// owner of token account containing master token (#8)
func (inst *MintNewEditionFromMasterEditionViaToken) GetOwnerOfTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[7]
}

// SetTokenAccount sets the "tokenAccount" account.
// token account containing token from master metadata mint
func (inst *MintNewEditionFromMasterEditionViaToken) SetTokenAccount(tokenAccount ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenAccount)
	return inst
}

// GetTokenAccount gets the "tokenAccount" account.
// token account containing token from master metadata mint
func (inst *MintNewEditionFromMasterEditionViaToken) GetTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[8]
}

// SetUpdateAuthorityInfoAccount sets the "updateAuthorityInfo" account.
// Update authority info for new metadata
func (inst *MintNewEditionFromMasterEditionViaToken) SetUpdateAuthorityInfoAccount(updateAuthorityInfo ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(updateAuthorityInfo)
	return inst
}

// GetUpdateAuthorityInfoAccount gets the "updateAuthorityInfo" account.
// Update authority info for new metadata
func (inst *MintNewEditionFromMasterEditionViaToken) GetUpdateAuthorityInfoAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[9]
}

// SetMasterRecordMetadataAccount sets the "masterRecordMetadata" account.
// Master record metadata account
func (inst *MintNewEditionFromMasterEditionViaToken) SetMasterRecordMetadataAccount(masterRecordMetadata ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(masterRecordMetadata)
	return inst
}

// GetMasterRecordMetadataAccount gets the "masterRecordMetadata" account.
// Master record metadata account
func (inst *MintNewEditionFromMasterEditionViaToken) GetMasterRecordMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[10]
}

// SetTokenProgramAccount sets the "tokenProgram" account.
// Token program
func (inst *MintNewEditionFromMasterEditionViaToken) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
// Token program
func (inst *MintNewEditionFromMasterEditionViaToken) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[11]
}

// SetSystemProgramAccount sets the "systemProgram" account.
// System program
func (inst *MintNewEditionFromMasterEditionViaToken) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
// System program
func (inst *MintNewEditionFromMasterEditionViaToken) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[12]
}

// SetRentInfoAccount sets the "rentInfo" account.
// Rent info
func (inst *MintNewEditionFromMasterEditionViaToken) SetRentInfoAccount(rentInfo ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(rentInfo)
	return inst
}

// GetRentInfoAccount gets the "rentInfo" account.
// Rent info
func (inst *MintNewEditionFromMasterEditionViaToken) GetRentInfoAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[13]
}

func (inst MintNewEditionFromMasterEditionViaToken) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.TypeIDFromUint8(Instruction_MintNewEditionFromMasterEditionViaToken),
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst MintNewEditionFromMasterEditionViaToken) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *MintNewEditionFromMasterEditionViaToken) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Args == nil {
			return errors.New("Args parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.NewMetadataKey is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.NewEditionPDA is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.MasterRecordEditionV2 is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.MintOfNewToken is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.EditionPDA is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.MintAuthority is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.OwnerOfToken is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenAccount is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.UpdateAuthorityInfo is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.MasterRecordMetadata is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.RentInfo is not set")
		}
	}
	return nil
}

func (inst *MintNewEditionFromMasterEditionViaToken) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("MintNewEditionFromMasterEditionViaToken")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Args", *inst.Args))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=14]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("       newMetadataKey", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("        newEditionPDA", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("masterRecordEditionV2", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("       mintOfNewToken", inst.AccountMetaSlice[3]))
						accountsBranch.Child(ag_format.Meta("           editionPDA", inst.AccountMetaSlice[4]))
						accountsBranch.Child(ag_format.Meta("        mintAuthority", inst.AccountMetaSlice[5]))
						accountsBranch.Child(ag_format.Meta("                payer", inst.AccountMetaSlice[6]))
						accountsBranch.Child(ag_format.Meta("         ownerOfToken", inst.AccountMetaSlice[7]))
						accountsBranch.Child(ag_format.Meta("                token", inst.AccountMetaSlice[8]))
						accountsBranch.Child(ag_format.Meta("  updateAuthorityInfo", inst.AccountMetaSlice[9]))
						accountsBranch.Child(ag_format.Meta(" masterRecordMetadata", inst.AccountMetaSlice[10]))
						accountsBranch.Child(ag_format.Meta("         tokenProgram", inst.AccountMetaSlice[11]))
						accountsBranch.Child(ag_format.Meta("        systemProgram", inst.AccountMetaSlice[12]))
						accountsBranch.Child(ag_format.Meta("             rentInfo", inst.AccountMetaSlice[13]))
					})
				})
		})
}

func (obj MintNewEditionFromMasterEditionViaToken) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Args` param:
	err = encoder.Encode(obj.Args)
	if err != nil {
		return err
	}
	return nil
}
func (obj *MintNewEditionFromMasterEditionViaToken) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Args`:
	err = decoder.Decode(&obj.Args)
	if err != nil {
		return err
	}
	return nil
}

// NewMintNewEditionFromMasterEditionViaTokenInstruction declares a new MintNewEditionFromMasterEditionViaToken instruction with the provided parameters and accounts.
func NewMintNewEditionFromMasterEditionViaTokenInstruction(
	// Parameters:
	args MintNewEditionFromMasterEditionViaTokenArgs,
	// Accounts:
	newMetadataKey ag_solanago.PublicKey,
	newEditionPDA ag_solanago.PublicKey,
	masterRecordEditionV2 ag_solanago.PublicKey,
	mintOfNewToken ag_solanago.PublicKey,
	editionPDA ag_solanago.PublicKey,
	mintAuthority ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	ownerOfToken ag_solanago.PublicKey,
	tokenAccount ag_solanago.PublicKey,
	updateAuthorityInfo ag_solanago.PublicKey,
	masterRecordMetadata ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rentInfo ag_solanago.PublicKey) *MintNewEditionFromMasterEditionViaToken {
	return NewMintNewEditionFromMasterEditionViaTokenInstructionBuilder().
		SetArgs(args).
		SetNewMetadataKeyAccount(newMetadataKey).
		SetNewEditionPDAAccount(newEditionPDA).
		SetMasterRecordEditionV2Account(masterRecordEditionV2).
		SetMintOfNewTokenAccount(mintOfNewToken).
		SetEditionPDAAccount(editionPDA).
		SetMintAuthorityAccount(mintAuthority).
		SetPayerAccount(payer).
		SetOwnerOfTokenAccount(ownerOfToken).
		SetTokenAccount(tokenAccount).
		SetUpdateAuthorityInfoAccount(updateAuthorityInfo).
		SetMasterRecordMetadataAccount(masterRecordMetadata).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetRentInfoAccount(rentInfo)
}
