// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package metaplex

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Initializes an Auction Manager V1
type DeprecatedInitAuctionManagerV1 struct {
	Args *AuctionManagerSettingsV1

	// [0] = [WRITE] uninitializedUnallocatedAuctionManager
	// ··········· Uninitialized, unallocated auction manager account with pda of ['metaplex', auction_key from auction referenced below]
	//
	// [1] = [] combinedVault
	// ··········· Combined vault account with authority set to auction manager account (this will be checked)
	// ··········· Note in addition that this vault account should have authority set to this program's pda of ['metaplex', auction_key]
	//
	// [2] = [] auction
	// ··········· Auction with auctioned item being set to the vault given and authority set to this program's pda of ['metaplex', auction_key]
	//
	// [3] = [] authority
	// ··········· Authority for the Auction Manager
	//
	// [4] = [SIGNER] payer
	// ··········· Payer
	//
	// [5] = [] acceptPayment
	// ··········· Accept payment account of same token mint as the auction for taking payment for open editions, owner should be auction manager key
	//
	// [6] = [] store
	// ··········· Store that this auction manager will belong to
	//
	// [7] = [] systemSysvar
	// ··········· System sysvar
	//
	// [8] = [] rentSysvar
	// ··········· Rent sysvar
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewDeprecatedInitAuctionManagerV1InstructionBuilder creates a new `DeprecatedInitAuctionManagerV1` instruction builder.
func NewDeprecatedInitAuctionManagerV1InstructionBuilder() *DeprecatedInitAuctionManagerV1 {
	nd := &DeprecatedInitAuctionManagerV1{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 9),
	}
	return nd
}

// SetArgs sets the "args" parameter.
func (inst *DeprecatedInitAuctionManagerV1) SetArgs(args AuctionManagerSettingsV1) *DeprecatedInitAuctionManagerV1 {
	inst.Args = &args
	return inst
}

// SetUninitializedUnallocatedAuctionManagerAccount sets the "uninitializedUnallocatedAuctionManager" account.
// Uninitialized, unallocated auction manager account with pda of ['metaplex', auction_key from auction referenced below]
func (inst *DeprecatedInitAuctionManagerV1) SetUninitializedUnallocatedAuctionManagerAccount(uninitializedUnallocatedAuctionManager ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(uninitializedUnallocatedAuctionManager).WRITE()
	return inst
}

// GetUninitializedUnallocatedAuctionManagerAccount gets the "uninitializedUnallocatedAuctionManager" account.
// Uninitialized, unallocated auction manager account with pda of ['metaplex', auction_key from auction referenced below]
func (inst *DeprecatedInitAuctionManagerV1) GetUninitializedUnallocatedAuctionManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetCombinedVaultAccount sets the "combinedVault" account.
// Combined vault account with authority set to auction manager account (this will be checked)
// Note in addition that this vault account should have authority set to this program's pda of ['metaplex', auction_key]
func (inst *DeprecatedInitAuctionManagerV1) SetCombinedVaultAccount(combinedVault ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(combinedVault)
	return inst
}

// GetCombinedVaultAccount gets the "combinedVault" account.
// Combined vault account with authority set to auction manager account (this will be checked)
// Note in addition that this vault account should have authority set to this program's pda of ['metaplex', auction_key]
func (inst *DeprecatedInitAuctionManagerV1) GetCombinedVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAuctionAccount sets the "auction" account.
// Auction with auctioned item being set to the vault given and authority set to this program's pda of ['metaplex', auction_key]
func (inst *DeprecatedInitAuctionManagerV1) SetAuctionAccount(auction ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(auction)
	return inst
}

// GetAuctionAccount gets the "auction" account.
// Auction with auctioned item being set to the vault given and authority set to this program's pda of ['metaplex', auction_key]
func (inst *DeprecatedInitAuctionManagerV1) GetAuctionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetAuthorityAccount sets the "authority" account.
// Authority for the Auction Manager
func (inst *DeprecatedInitAuctionManagerV1) SetAuthorityAccount(authority ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
// Authority for the Auction Manager
func (inst *DeprecatedInitAuctionManagerV1) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPayerAccount sets the "payer" account.
// Payer
func (inst *DeprecatedInitAuctionManagerV1) SetPayerAccount(payer ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(payer).SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
// Payer
func (inst *DeprecatedInitAuctionManagerV1) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetAcceptPaymentAccount sets the "acceptPayment" account.
// Accept payment account of same token mint as the auction for taking payment for open editions, owner should be auction manager key
func (inst *DeprecatedInitAuctionManagerV1) SetAcceptPaymentAccount(acceptPayment ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(acceptPayment)
	return inst
}

// GetAcceptPaymentAccount gets the "acceptPayment" account.
// Accept payment account of same token mint as the auction for taking payment for open editions, owner should be auction manager key
func (inst *DeprecatedInitAuctionManagerV1) GetAcceptPaymentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStoreAccount sets the "store" account.
// Store that this auction manager will belong to
func (inst *DeprecatedInitAuctionManagerV1) SetStoreAccount(store ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(store)
	return inst
}

// GetStoreAccount gets the "store" account.
// Store that this auction manager will belong to
func (inst *DeprecatedInitAuctionManagerV1) GetStoreAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSystemSysvarAccount sets the "systemSysvar" account.
// System sysvar
func (inst *DeprecatedInitAuctionManagerV1) SetSystemSysvarAccount(systemSysvar ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemSysvar)
	return inst
}

// GetSystemSysvarAccount gets the "systemSysvar" account.
// System sysvar
func (inst *DeprecatedInitAuctionManagerV1) GetSystemSysvarAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetRentSysvarAccount sets the "rentSysvar" account.
// Rent sysvar
func (inst *DeprecatedInitAuctionManagerV1) SetRentSysvarAccount(rentSysvar ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(rentSysvar)
	return inst
}

// GetRentSysvarAccount gets the "rentSysvar" account.
// Rent sysvar
func (inst *DeprecatedInitAuctionManagerV1) GetRentSysvarAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

func (inst DeprecatedInitAuctionManagerV1) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.TypeIDFromUint8(Instruction_DeprecatedInitAuctionManagerV1),
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst DeprecatedInitAuctionManagerV1) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *DeprecatedInitAuctionManagerV1) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Args == nil {
			return errors.New("Args parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.UninitializedUnallocatedAuctionManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CombinedVault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Auction is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.AcceptPayment is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Store is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemSysvar is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.RentSysvar is not set")
		}
	}
	return nil
}

func (inst *DeprecatedInitAuctionManagerV1) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("DeprecatedInitAuctionManagerV1")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Args", *inst.Args))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=9]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("uninitializedUnallocatedAuctionManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                         combinedVault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("                               auction", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                             authority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                                 payer", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                         acceptPayment", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                                 store", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("                          systemSysvar", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("                            rentSysvar", inst.AccountMetaSlice.Get(8)))
					})
				})
		})
}

func (obj DeprecatedInitAuctionManagerV1) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Args` param:
	err = encoder.Encode(obj.Args)
	if err != nil {
		return err
	}
	return nil
}
func (obj *DeprecatedInitAuctionManagerV1) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Args`:
	err = decoder.Decode(&obj.Args)
	if err != nil {
		return err
	}
	return nil
}

// NewDeprecatedInitAuctionManagerV1Instruction declares a new DeprecatedInitAuctionManagerV1 instruction with the provided parameters and accounts.
func NewDeprecatedInitAuctionManagerV1Instruction(
	// Parameters:
	args AuctionManagerSettingsV1,
	// Accounts:
	uninitializedUnallocatedAuctionManager ag_solanago.PublicKey,
	combinedVault ag_solanago.PublicKey,
	auction ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	acceptPayment ag_solanago.PublicKey,
	store ag_solanago.PublicKey,
	systemSysvar ag_solanago.PublicKey,
	rentSysvar ag_solanago.PublicKey) *DeprecatedInitAuctionManagerV1 {
	return NewDeprecatedInitAuctionManagerV1InstructionBuilder().
		SetArgs(args).
		SetUninitializedUnallocatedAuctionManagerAccount(uninitializedUnallocatedAuctionManager).
		SetCombinedVaultAccount(combinedVault).
		SetAuctionAccount(auction).
		SetAuthorityAccount(authority).
		SetPayerAccount(payer).
		SetAcceptPaymentAccount(acceptPayment).
		SetStoreAccount(store).
		SetSystemSysvarAccount(systemSysvar).
		SetRentSysvarAccount(rentSysvar)
}
